/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const BaseButton: typeof import('../components/atoms/BaseButton/index')['default']
  const BaseFlexBox: typeof import('../components/atoms/BaseFlexBox/index')['default']
  const BaseIcon: typeof import('../components/atoms/BaseIcon/index')['default']
  const BaseInput: typeof import('../components/atoms/BaseInput/index')['default']
  const BaseLoading: typeof import('../components/atoms/BaseLoading/index')['default']
  const BaseModal: typeof import('../components/atoms/BaseModal/index')['default']
  const BaseTypography: typeof import('../components/atoms/BaseTypography/index')['default']
  const CountNumber: typeof import('../components/molecules/CountNumber/index')['default']
  const Header: typeof import('../components/organisms/Header/index')['default']
  const PickSize: typeof import('../components/molecules/PickSize/index')['default']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const startTransition: typeof import('react')['startTransition']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useRouter: typeof import('next/router')['useRouter']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { FunctionComponent, FC } from 'react'
  import('react')
}
