/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const BaseButton: typeof import('../components/ui/BaseButton/index')['default']
  const BaseFlexBox: typeof import('../components/ui/BaseFlexBox/index')['default']
  const BaseIcon: typeof import('../components/ui/BaseIcon/index')['default']
  const BaseInput: typeof import('../components/ui/BaseInput/index')['default']
  const BaseLoading: typeof import('../components/ui/BaseLoading/index')['default']
  const BaseModal: typeof import('../components/ui/BaseModal/index')['default']
  const BaseTable: typeof import('../components/ui/BaseTable/index')['default']
  const BaseTypography: typeof import('../components/ui/BaseTypography/index')['default']
  const Card: typeof import('../components/ui/Card/index')['default']
  const Container: typeof import('../components/Container/index')['default']
  const CountNumber: typeof import('../components/features/CountNumber/index')['default']
  const FooterMain: typeof import('../components/ui/FooterMain/index')['default']
  const FooterMainInfo: typeof import('../components/ui/FooterMainInfo/index')['default']
  const FooterMainLink: typeof import('../components/ui/FooterMainLink/index')['default']
  const FooterMainTop: typeof import('../components/ui/FooterMainTop/index')['default']
  const Header: typeof import('../components/ui/Header/index')['default']
  const HeaderMainMenu: typeof import('../components/ui/HeaderMainMenu/index')['default']
  const PickSize: typeof import('../components/features/PickSize/index')['default']
  const SideBar: typeof import('../components/ui/SideBar/index')['default']
  const SliderImage: typeof import('../components/ui/SliderImage/index')['default']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const startTransition: typeof import('react')['startTransition']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useRouter: typeof import('next/router')['useRouter']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { FunctionComponent, FC } from 'react'
  import('react')
}
